#!/usr/bin/env bash

echo "# run tasks"
echo ""

BASE_PATH=$(dirname $(realpath -s $0) | sed "s:/scripts::g")
MASTER_CNF_PATH=$BASE_PATH/data/config/master.cnf

for task in tasks/*
do
	./$task $MASTER_CNF_PATH $BASE_PATH
	read -t 2 -p ""
done

echo ""
echo "# finished"
echo ""
