name: Test Recipes

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate recipes.yaml
        run: |
          python3 -c "import yaml; yaml.safe_load(open('recipes.yaml')); print('✅ recipes.yaml is valid')"
      
      - name: Check recipe files exist
        run: |
          echo "Checking all recipe files exist..."
          python3 -c "
          import yaml, os
          data = yaml.safe_load(open('recipes.yaml'))
          missing = []
          for recipe in data['recipes']:
              script_path = 'recipes/' + recipe['script']
              if not os.path.exists(script_path):
                  missing.append(script_path)
                  print(f'❌ Missing: {script_path}')
              else:
                  print(f'✓ Found: {script_path}')
          if missing: exit(1)
          else: print('✅ All recipe files exist')
          "

  test-recipes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe:
          - base
          - wifi
          - git
          - ripgrep
          - jaq
          - lazygit
          - fzf
          - gh
          - golang
          - rust
          - nvm
          - bruno
          - cursor
          - cascadia-font
          - youtube-downloader
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Create test machine directory
        run: |
          chmod +x resetup
          ./resetup init test-machine
      
      - name: Test recipe - ${{ matrix.recipe }}
        run: |
          chmod +x tests/test-recipe.sh
          ./tests/test-recipe.sh ${{ matrix.recipe }}

  test-encryption:
    runs-on: ubuntu-latest
    # Force refresh of workflow cache
    steps:
      - uses: actions/checkout@v4
      
      - name: Create test machine data
        run: |
          chmod +x resetup
          ./resetup init test-machine
          
          # Add additional test files
          echo "test-key" > machines/test-machine/files/.ssh/test_key
      
      - name: Test encryption/decryption
        run: |
          # Test encryption using machine-based structure
          echo "# encrypt machine data"
          tar -czf test-machine.tar.gz machines/test-machine/ > /dev/null
          openssl aes256 -pbkdf2 -salt -in test-machine.tar.gz -out machines/test-machine.aes256 -pass pass:test-password
          rm test-machine.tar.gz
          echo "✅ Encryption successful"
          
          # Verify encrypted file exists
          if [ ! -f "machines/test-machine.aes256" ]; then
            echo "❌ Encryption failed - machines/test-machine.aes256 not found"
            exit 1
          fi
          
          # Remove original machine data
          rm -rf machines/test-machine/
          
          # Test decryption
          openssl enc -d -aes256 -pbkdf2 -salt -in machines/test-machine.aes256 -out test-machine.tar.gz -pass pass:test-password
          tar -xzf test-machine.tar.gz
          rm test-machine.tar.gz
          
          # Verify decryption
          if [ ! -f "machines/test-machine/master.cnf" ]; then
            echo "❌ Decryption failed"
            exit 1
          fi
          
          echo "✅ Encryption/decryption test passed"

  test-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check circular dependencies
        run: |
          python3 tests/check-dependencies.py
      
      - name: Test dependency resolution
        run: |
          # Test that dependencies are properly resolved
          chmod +x tests/test-dependencies.sh
          ./tests/test-dependencies.sh

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create test environment
        run: |
          chmod +x resetup
          ./resetup init test-machine
          
          # Create dummy SSH key for testing
          ssh-keygen -t ed25519 -f machines/test-machine/files/.ssh/id_ed25519 -N "" -C "test@example.com"
      
      - name: Run integration test
        run: |
          chmod +x tests/integration-test.sh
          ./tests/integration-test.sh