name: Test Recipes

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      
      - name: Validate recipes.yaml
        run: |
          yq eval '.' recipes.yaml > /dev/null
          echo "✅ recipes.yaml is valid"
      
      - name: Check recipe files exist
        run: |
          echo "Checking all recipe files exist..."
          for recipe in $(yq eval '.recipes[].script' recipes.yaml); do
            if [ ! -f "recipes/$recipe" ]; then
              echo "❌ Missing recipe file: recipes/$recipe"
              exit 1
            fi
            echo "✓ Found: recipes/$recipe"
          done
          echo "✅ All recipe files exist"

  test-recipes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe:
          - base
          - wifi
          - git
          - ripgrep
          - jaq
          - lazygit
          - fzf
          - gh
          - golang
          - rust
          - nvm
          - bruno
          - cursor
          - cascadia-font
          - clickup
          - youtube-downloader
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Create test data directory
        run: |
          mkdir -p data/config
          cp data/config/master.cnf.default data/config/master.cnf
      
      - name: Test recipe - ${{ matrix.recipe }}
        run: |
          chmod +x tests/test-recipe.sh
          ./tests/test-recipe.sh ${{ matrix.recipe }}

  test-encryption:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create test data
        run: |
          mkdir -p data/config data/files/.ssh
          cp data/config/master.cnf.default data/config/master.cnf
          
          # Create test SSH config
          cat > data/files/.ssh/config << 'EOF'
          Host *
              AddKeysToAgent yes
              UseKeychain yes
              IdentityFile ~/.ssh/id_rsa
          EOF
          
          echo "test-key" > data/files/.ssh/test_key
      
      - name: Test encryption/decryption
        run: |
          # Test pack script
          echo "test-password" | ./pack
          
          # Verify encrypted file exists
          if [ ! -f "data.aes256" ]; then
            echo "❌ Encryption failed - data.aes256 not found"
            exit 1
          fi
          
          # Remove original data
          rm -rf data/
          
          # Test unpack (decryption only, not full install)
          mkdir -p scripts
          cat > scripts/test-dec << 'EOF'
          #!/usr/bin/env bash
          echo "test-password" | openssl enc -d -aes256 -pbkdf2 -salt -in data.aes256 -out data.tar.gz
          tar -xzvf data.tar.gz
          rm data.tar.gz
          EOF
          chmod +x scripts/test-dec
          ./scripts/test-dec
          
          # Verify decryption
          if [ ! -f "data/config/master.cnf" ]; then
            echo "❌ Decryption failed"
            exit 1
          fi
          
          echo "✅ Encryption/decryption test passed"

  test-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      
      - name: Check circular dependencies
        run: |
          python3 tests/check-dependencies.py
      
      - name: Test dependency resolution
        run: |
          # Test that dependencies are properly resolved
          chmod +x tests/test-dependencies.sh
          ./tests/test-dependencies.sh

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create test environment
        run: |
          # Create full test data structure
          mkdir -p data/config data/files/.ssh
          cp data/config/master.cnf.default data/config/master.cnf
          
          # Create test SSH config
          cat > data/files/.ssh/config << 'EOF'
          Host *
              AddKeysToAgent yes
              UseKeychain yes
              IdentityFile ~/.ssh/id_rsa
          EOF
          
          # Create dummy SSH key
          ssh-keygen -t ed25519 -f data/files/.ssh/id_ed25519 -N "" -C "test@example.com"
      
      - name: Run integration test
        run: |
          chmod +x tests/integration-test.sh
          ./tests/integration-test.sh